{% set name = "array-api-compat" %}
{% set version = "1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/array_api_compat-{{ version }}.tar.gz
  sha256: 8fb35f2895822b1cc6618449efd84aa76dcea1ab96940304f869663fd6a0dcd8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - array_api_compat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://data-apis.org/array-api-compat/
  summary: A wrapper around NumPy and other array libraries to make them compatible with the Array API standard
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asmeurer
    - rgommers
