{% set name = "array-api-compat" %}
{% set version = "1.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/array_api_compat-{{ version }}.tar.gz
  sha256: 53c5f922491bf15f62847afafc4e39eedfae57d218988fefb8cce39c2a9b3dea

build:
  number: 0
  skip: true # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - meson-python
    - meson
    - ninja
  run:
    - python

test:
  source_files:
    - tests
    - pyproject.toml
  imports:
    - array_api_compat
    - array_api_compat.common
  requires:
    - pip
    - pytest
    - numpy
  commands:
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pip check
    - pytest -v tests

about:
  home: https://github.com/data-apis/array-api-compat
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A wrapper around NumPy and other array libraries to make them compatible with the Array API standard
  description: |
    This is a small wrapper around common array libraries that is compatible with the Array API
    standard. Currently, NumPy, CuPy, PyTorch, Dask, JAX, ndonnx, and Sparse are supported.
  doc_url: https://data-apis.org/array-api-compat
  dev_url: https://github.com/data-apis/array-api-compat

extra:
  recipe-maintainers:
    - lucascolley
    - asmeurer
    - rgommers