{% set name = "array-api-compat" %}
{% set version = "1.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/array_api_compat-{{ version }}.tar.gz
  sha256: 9d80383f5a52a3adb09c3e0a062b0be168761e4b8d7079cfea1f7387fc2eae63

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - array_api_compat
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://data-apis.org/array-api-compat/
  summary: A wrapper around NumPy and other array libraries to make them compatible with the Array API standard
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lucascolley
    - asmeurer
    - rgommers
