{% set name = "array-api-compat" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/array_api_compat-{{ version }}.tar.gz
  sha256: 17bab828c93c79a5bb8b867145b71fcb889686607c5672b060aef437e0359ea8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - array_api_compat
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://data-apis.org/array-api-compat/
  summary: A wrapper around NumPy and other array libraries to make them compatible with the Array API standard
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asmeurer
    - rgommers
