schema_version: 1

context:
  name: array-api-compat
  version: "1.11.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/array_api_compat-${{ version }}.tar.gz
  sha256: a3b7f7b6af18f4c42e79423b1b2479798998b6a74355069d77a01a5282755b5d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - array_api_compat
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: A wrapper around NumPy and other array libraries to make them compatible with the Array API standard
  license: MIT
  license_file: LICENSE
  homepage: https://data-apis.org/array-api-compat/

extra:
  recipe-maintainers:
    - lucascolley
    - asmeurer
    - rgommers
